# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &jaimek age1rmj3fw2p7eymf7c0n40sgxxrh0x4uzdykvst4wr6usn4zlqrcpvst5jr4k
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *jaimek
