# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b95373d9-0482-48dc-a316-26e1758ce248";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B265-F7CA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7966d6aa-5971-4c6f-8d44-f187066084e6";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/15cb4912-0eb5-4d17-8b2c-267a6995c369";
      fsType = "ext4";
    };

  swapDevices = [ ];


# from vimjoyer https://www.youtube.com/watch?v=qlfm3MEbqYA
hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
};

services.xserver.videoDrivers = [ "nvidia" ];

hardware.nvidia = {

	modesetting.enable = true;

	package = config.boot.kernelPackages.nvidiaPackages.stable;
# 	prime = {
# 		sync.enable = true;
#
# # dedicated
# 		nvidiaBusId = "PCI:6:0:0";
# 	};
};

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
