theme = "stylix"
 client_id = "9328d153206d485d8c492839ef2b2bfe"
client_port = 8888
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
cover_img_length = 10
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_notify = false
enable_media_control = false
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "nixos"

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[device]
name = "nixos"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false

